### ISSUE TITLE
Dropdown doesn't close when selection is made

### ISSUE THREAD

**Issue by sheldonlendrum** [FinesseRus/froala-editor-paragraph-format-extended-plugin#1]
Using this on Froala version 3.0.1. 
I have my paragraphFormatExtended plugin enabled and showing by custom heading options. 

When I select an option, it applies the style but does not close the dropdown. 
To close it, I must click the toolbar icon two times. 

No JS error in console.

**Comment by Finesse** [comment]
I can't reproduce it: https://codepen.io/TheFinesse/pen/zYvRLjN?editors=1010

Please provide a reproducible demo or check that:

- The Froala plugins like `paragraphFormat` and `paragraphStyle` don't have this bug
- Nothing interferes the editor in your application

**Comment by sheldonlendrum** [comment]
Looks like it was my version of Froala, I have 3.0.0 not 3.0.1
Working in newer versions, but need to update my license
